log_level: INFO

repository:
  object_storage: s3://neptune-tests-locks
  stacks_management: local
  branch: main
  plan_requirements:
    - undiverged
  apply_requirements: []
  allowed_workflow: default
  automerge: true

workflows:
  default:
    plan:
      steps:
        - run: terragrunt init -upgrade
        - run: terragrunt plan
    apply:
      depends_on:
        - plan
      steps:
        - run: terragrunt apply -auto-approve
